[tox]
envlist = build, test
runner = uv-venv-runner


[testenv]
skip_install = True
changedir = {toxinidir}
passenv = https_proxy, http_proxy, no_proxy, SURREALDB_PASSWORD


[testenv:run]
skip_install = False
deps =
    ipdb
commands =
    surrealdb_migrations -vvv {posargs}


[testenv:run-db]
allowlist_externals =
    docker
commands =
    docker run \
        --rm \
        --pull always \
        --name surrealdb \
        -p 8000:8000 \
        surrealdb/surrealdb:latest \
        start --log debug --user root --pass root memory


[testenv:build]
commands =
    uv build


[testenv:build-container]
allowlist_externals =
    docker
commands =
    docker build --file {toxinidir}/deployment/docker/Dockerfile {toxinidir} {posargs:--tag surrealdb_migrations:latest}


[testenv:test]
skip_install = False
changedir = {envtmpdir}
deps =
    -rtest/requirements.txt
allowlist_externals =
    rm
commands =
    # Check style
    flake8 {toxinidir}

    # Clean testing cache
    rm -rf {toxinidir}/test/__pycache__

    # Run test suite
    py.test -s \
        --junitxml=tests.xml \
        --cov=surrealdb_migrations \
        --cov-report xml \
        --cov-report html \
        --cov-report term \
        {posargs} \
        {toxinidir}/test


[testenv:publish]
deps =
    twine
allowlist_externals =
    ls
commands =
    uv build
    ls -lh {toxinidir}/dist/
    {envpython} -c "print((\
        'Packages ready. '\
        'Execute the following command to publish:\n'\
        '    twine upload --repository pypi --skip-existing dist/*'\
    ))"


[flake8]
exclude = .git,.tox,.cache,__pycache__,dist,build,*.egg-info
